### ISSUE TITLE
Acrescentar dinheiro do banco

### ISSUE THREAD

**Issue by BurgosNY** [Petesuchos/vrbr18xx#1]
No Gamestate, __init__ da classe, seria interessante colocar mais dois atributos da classe: number_of_players, bank_cash

if number_of_players = 3: bank_cash=6500, (4, 7500, 5, 9000, etc)

**Comment by Petesuchos** [comment]
Funcionalidade acrescentada.

Mas ela não está no init da classe Gamestate por que o número de jogadores só é fechado quando se inicia a SR1, então a implementação ficou no set_stock_round.
